FROM ubuntu:latest
LABEL desc="this is my ubuntu web server"
LABEL author="ani"

RUN apt-get update -y && apt-get install nginx -y
COPY index.html /var/www/html/

WORKDIR /tmp

ENV varname="ram"
ENV varpass="123"
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
~                                   